Console.WriteLine ("**************DESAFIO******************");
string firstName3;
firstName3 = "Bob";
//Console.WriteLine (firstName);
int num=3;
//Console.WriteLine (num);
//float tem = 34.4f;
//Console.WriteLine (tem);
var tem2 = 34.4;
//Console.WriteLine (tem2);
Console.WriteLine ("Hello,"+ firstName3 + ",! You have"+ num + "messages in your inbox. The temperature is"+tem2+ "celsius.");